import { Audio } from "@remotion/media";
import { AbsoluteFill } from "remotion";
import { ASSETS } from "./assets";
import { Grain } from "./components/Chrome";
import { Scene } from "./components/Scene";
import { sceneEnd, sceneStart } from "./lib/motion";
import { CategoriesScene } from "./scenes/CategoriesScene";
import { EndCardScene } from "./scenes/EndCardScene";
import { HookScene } from "./scenes/HookScene";
import { OffersScene } from "./scenes/OffersScene";
import { ProductsScene } from "./scenes/ProductsScene";
import { StatementScene } from "./scenes/StatementScene";
import { C } from "./theme";

/**
 * CHIPKU promo reel — 1920×1080, 30 fps, exactly 600 frames (20 s).
 * Three beats: intro (hook + products) → categories + bundle offers → CTA.
 * All timing comes from src/timeline.json, which also drives audio/generate_audio.py.
 */
export const ChipkuReel: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: C.ink }}>
    <Scene name="01 Hook" start={sceneStart("hook")} end={sceneEnd("hook")}>
      <HookScene />
    </Scene>
    <Scene name="02 Products" start={sceneStart("products")} end={sceneEnd("products")}>
      <ProductsScene />
    </Scene>
    <Scene name="03 Categories" start={sceneStart("categories")} end={sceneEnd("categories")}>
      <CategoriesScene />
    </Scene>
    <Scene name="04 Offers" start={sceneStart("offers")} end={sceneEnd("offers")}>
      <OffersScene />
    </Scene>
    <Scene name="05 Statement" start={sceneStart("statement")} end={sceneEnd("statement")}>
      <StatementScene />
    </Scene>
    <Scene name="06 End card" start={sceneStart("endcard")} end={sceneEnd("endcard")}>
      <EndCardScene />
    </Scene>
    <Grain />
    {/* Premixed soundtrack (music + synced SFX) generated by audio/generate_audio.py */}
    <Audio name="Soundtrack" src={ASSETS.soundtrack} />
  </AbsoluteFill>
);
